repositories:
  # Local repository with our favorite photos and videos.
  Local storage:
    type: local
    root: /usr/local/share/photos
  # WebDAV repository with the latest photos from our smartphone.
  Cloud storage:
    type: webdav
    url: https://mycloud.mydomain.org
    root: /remote.php/webdav/photos
    user: frame
    password: <password>
  # Test repository, which has been disabled.
  Test repository:
    type: local
    root: ./local/test
    enabled: false

slideshows:
  # Slideshow with our favorite photos and videos.
  Favorites:
    repositories: Local storage
    pause: 60
    tags: favorites
  # Slideshow with most recent photos from our smartphone.
  Recent:
    repositories: Cloud storage
    excluded_tags:
      - vacation
      - favorites
    types: images
    most_recent: 200
    order: date
    direction: descending

# Slideshow defaults
always_excluded_tags: private
label_content: description
label_mode: auto
label_duration: 30
orientation: portrait
pause: 180

schedule:
  # Play the slideshow "Recent" in the period from 8:00 to 10:00.
  morning start:
    time: "08:00"
    slideshow: Recent
    play_state: playing
  morning stop:
    time: "10:00"
    play_state: stopped
  # Play the slideshow "Favorites" in the period from 18:00 to 20:00.
  # Do not play automatically, but activate via motion sensor.
  evening start:
    time: "18:00"
    slideshow: Favorites
    play_state: paused
  evening stop:
    time: "20:00"
    play_state: stopped

mqtt:
  host: mqtt.local
  port: 8883
  tls: true
  user: frame
  password: <my password>
  device_id: frame
  device_name: My digital photo frame somwhere in the house
