name: Changelog
on:
  workflow_dispatch:
    inputs:
      user: kalbfuss
      project: 01memories
      output: CHANGELOG.md
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
